# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'agencies',
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'city',
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'drivers',
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Fuels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'fuels',
                'verbose_name': 'Fuel',
                'verbose_name_plural': 'Fuel',
            },
        ),
        migrations.CreateModel(
            name='FuelStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('city', models.ForeignKey(blank=True, db_column=b'city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.City')),
            ],
            options={
                'db_table': 'fuel_stations',
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
                ('agency', models.ForeignKey(blank=True, db_column=b'agency', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Agencies')),
            ],
            options={
                'db_table': 'sectors',
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('uf', models.CharField(blank=True, max_length=5, null=True)),
                ('country', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'states',
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('liters', models.IntegerField(blank=True, null=True)),
                ('auto_date', models.DateTimeField()),
                ('driver', models.ForeignKey(blank=True, db_column=b'driver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Drivers')),
                ('fuel_station', models.ForeignKey(blank=True, db_column=b'fuel_station', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.FuelStations')),
            ],
            options={
                'db_table': 'supplies',
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
            },
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(blank=True, null=True)),
                ('destiny', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, db_column=b'driver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Drivers')),
            ],
            options={
                'db_table': 'travels',
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.CharField(max_length=160)),
                ('password', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'users',
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, max_length=160, null=True)),
                ('chassis', models.CharField(max_length=160)),
                ('auto_date', models.DateTimeField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('km', models.CharField(blank=True, max_length=160, null=True)),
                ('ano', models.TextField(blank=True, null=True)),
                ('km_per_liter', models.IntegerField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('renavan', models.CharField(blank=True, max_length=160, null=True)),
                ('kind', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('ano_fab', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehiclesBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'vehicles_brands',
                'verbose_name': 'Vehicle Brand',
                'verbose_name_plural': 'Vehicle Brands',
            },
        ),
        migrations.CreateModel(
            name='VehiclesModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('brand', models.ForeignKey(blank=True, db_column=b'brand', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.VehiclesBrands')),
            ],
            options={
                'db_table': 'vehicles_models',
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
            },
        ),
        migrations.CreateModel(
            name='VehiclesProvenances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'vehicles_provenances',
                'verbose_name': 'Vehicle Provenance',
                'verbose_name_plural': 'Vehicle Provenances',
            },
        ),
        migrations.CreateModel(
            name='VehiclesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'vehicles_status',
                'verbose_name': 'Vehicle Status',
                'verbose_name_plural': 'Vehicle Status',
            },
        ),
        migrations.AddField(
            model_name='vehicles',
            name='conservation',
            field=models.ForeignKey(blank=True, db_column=b'conservation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.VehiclesStatus'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='fuel',
            field=models.ForeignKey(blank=True, db_column=b'fuel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Fuels'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='model',
            field=models.ForeignKey(blank=True, db_column=b'model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.VehiclesModels'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='provenance',
            field=models.ForeignKey(blank=True, db_column=b'provenance', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.VehiclesProvenances'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='sector',
            field=models.ForeignKey(db_column=b'sector', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sectors'),
        ),
        migrations.AddField(
            model_name='travels',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_column=b'vehicle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Vehicles'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_column=b'vehicle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Vehicles'),
        ),
        migrations.AddField(
            model_name='drivers',
            name='sector',
            field=models.ForeignKey(blank=True, db_column=b'sector', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sectors'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, db_column=b'state', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.States'),
        ),
    ]
